# Generated by Django 3.2 on 2021-04-25 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=355)),
                ('Category_Picture', models.ImageField(upload_to='CategoryImages/')),
                ('Category_description', models.CharField(max_length=3555)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=355)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='CustomerProfiles/')),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('Primary_shipping_address', models.CharField(blank=True, max_length=355, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=355)),
                ('Description', models.CharField(max_length=3555)),
                ('Release_date', models.DateTimeField(auto_now_add=True)),
                ('Made_in', models.CharField(blank=True, max_length=355, null=True)),
                ('Main_picture', models.ImageField(upload_to='ProductPhotos/')),
                ('Second_picture', models.ImageField(blank=True, null=True, upload_to='ProductPhotos/')),
                ('Third_picture', models.ImageField(blank=True, null=True, upload_to='ProductPhotos/')),
                ('Forth_picture', models.ImageField(blank=True, null=True, upload_to='ProductPhotos/')),
                ('Fifth_picture', models.ImageField(blank=True, null=True, upload_to='ProductPhotos/')),
                ('First_video', models.FileField(blank=True, null=True, upload_to='ProductVideos/')),
                ('Second_video', models.FileField(blank=True, null=True, upload_to='ProductVideos/')),
                ('Stock', models.IntegerField()),
                ('Expire_date', models.DateField(blank=True, null=True)),
                ('Category_Of_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=355)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='SellerProfiles/')),
                ('Varified', models.BooleanField(default=False, editable=False)),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=355)),
                ('Color_HEX', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Common_title', models.CharField(max_length=355)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Region', models.CharField(max_length=355)),
                ('Cost', models.PositiveIntegerField()),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.CharField(blank=True, max_length=3555, null=True)),
                ('By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='Tag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag1', to='api.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='Tag2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag2', to='api.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='Tag3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag3', to='api.tag'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammount', models.IntegerField(default=1)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
