# Generated by Django 3.2 on 2021-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210425_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
