# Generated by Django 3.2 on 2021-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='adimages/')),
                ('On_click_url', models.CharField(max_length=2555)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='bannerimages/')),
                ('On_click_url', models.CharField(max_length=3555)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'Release_date'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='Third_picture',
        ),
    ]
