# Generated by Django 3.2 on 2021-04-27 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210427_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'get_latest_by': 'Creation_date'},
        ),
        migrations.AddField(
            model_name='banner',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
