# Generated by Django 3.2 on 2021-04-28 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210427_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
