# Generated by Django 3.2 on 2021-04-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ad_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='adimages/')),
                ('On_click_url', models.CharField(max_length=3555)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ad',
            new_name='AdSmall',
        ),
    ]
