# Generated by Django 3.2 on 2021-04-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210428_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdBig',
        ),
        migrations.DeleteModel(
            name='AdSmall',
        ),
    ]
