# Generated by Django 3.2 on 2021-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210429_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Third_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ProductPhotos/'),
        ),
    ]
