# Generated by Django 3.2 on 2021-05-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='Product',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.variations'),
        ),
    ]
